# Generated by Django 4.2.7 on 2023-11-25 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Name')),
                ('stock_in_kg', models.FloatField(blank=True, null=True, verbose_name='Stock in KG')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Images')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Product Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('delivery_available', models.BooleanField(default=False, verbose_name='Delivery Available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farm_app.category', verbose_name='Product Category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
        ),
    ]
