# Generated by Django 4.2.7 on 2023-11-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
