# Generated by Django 4.2.7 on 2024-01-01 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0005_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_app.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to=settings.AUTH_USER_MODEL, verbose_name='Purchaser')),
            ],
        ),
    ]
